version: '3.10'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  
  db:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: kais_hasan
      POSTGRES_DB: e_market_postgres_db
      POSTGRES_PASSWORD: 12345678ABC
    
    volumes:
      - ./data:/var/lib/postgresql/data
