# Generated by Django 4.0.4 on 2022-05-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='money',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
