# Generated by Django 4.0.4 on 2022-04-30 14:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='new_id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
