# Generated by Django 4.0.4 on 2022-05-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_date_created_review_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
