# Generated by Django 4.0.4 on 2022-04-30 14:45

from django.db import migrations
import uuid


def populate_uuid(apps, schema_editor):
    Review = apps.get_model('reviews', 'Review')
    for review in Review.objects.all():
        review.new_id = uuid.uuid4()
        review.save()



class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_new_id'),
    ]

    operations = [
        migrations.RunPython(populate_uuid)
    ]
