# Generated by Django 4.0.4 on 2022-04-30 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_remove_review_id_alter_review_new_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='new_id',
            new_name='id',
        ),
    ]
