# Generated by Django 4.0.4 on 2022-04-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='num_items',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='number of items'),
        ),
    ]
