# Generated by Django 4.0.4 on 2022-04-27 16:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
