# Generated by Django 4.0.4 on 2022-04-27 16:38

from django.db import migrations
import uuid


def populate_uuid(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    for product in Product.objects.all():
        product.new_id = uuid.uuid4()
        product.save()

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_new_id'),
    ]

    operations = [
        migrations.RunPython(populate_uuid)
    ]
