# Generated by Django 4.0.4 on 2022-04-27 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_id_alter_product_new_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='new_id',
            new_name='id',
        ),
    ]
