# Generated by Django 4.0.4 on 2022-04-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_new_id_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='starred',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
